### Create Credit Transaction
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "id": "{{$guid}}",
  "amount": 100,
  "type": "credit"
}

### Create Debit Transaction
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "id": "{{$guid}}",
  "amount": 50,
  "type": "debit"
}

### Get Balance
GET http://localhost:3000/transactions/balance
Content-Type: application/json

### Rebuild State
POST http://localhost:3000/transactions/rebuild
Content-Type: application/json