### Get Order
GET http://localhost:3000/orders/3ae52544-33b1-4ba2-b258-6a097e47e389
Content-Type: application/json

### Create Order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "customerId": "{{$guid}}",
  "items": [
    {
      "productId": "{{$guid}}",
      "quantity": 2,
      "price": 100
    },
    {
      "productId": "{{$guid}}",
      "quantity": 1,
      "price": 200
    }
  ]
}