version: '3'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRES_IN_MINUTES: ${JWT_EXPIRES_IN_MINUTES}
        JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
        JWT_REFRESH_EXPIRES_IN_MINUTES: ${JWT_REFRESH_EXPIRES_IN_MINUTES}
    ports:
      - "3000:3000"
    env_file:
      - .env
